name: perch-agile-modeling
dependencies:
  - python=3.11
  - pip
  - pip:
    - numpy
    - pandas
    - polars
    - matplotlib
    - tensorflow[and-cuda]
    - git+https://github.com/google-research/perch.git